feat: Added weight markers to DirectoryTree.ts
hpcc-systems/Visualization pull request #3701
Opened 2020-09-08 16:03 UTC by jbrundage

Fixed HTMLTooltip.ts sizing bug
Added markerTextAlign to codemirror_Editor
Added fontFamily, fontSize, onmouseenter and onmouseleave to codemirror_Editor addGutterMarker method

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2020-09-08 16:20 UTC, GordonSmith requested changes
Minor:  use d3.Max.

2020-09-08 16:20 UTC, GordonSmith commented on packages/tree/src/DirectoryTree.ts
> +        const maxWeightValue = Math.max(...flatData.map(n=>Number(n.weightValue)));
Potentially expensive - could use d3.Max?

2020-09-08 16:20 UTC, GordonSmith commented on packages/tree/src/DirectoryTree.ts
> +        }));
d3.Max would be more efficient

2020-09-08 17:30 UTC, jbrundage commented
@GordonSmith I've changed it to use d3 max

2020-09-09 07:33 UTC, GordonSmith requested changes

2020-09-09 07:33 UTC, GordonSmith commented on packages/tree/src/DirectoryTree.ts
> +        const maxWeightValue = max(flatData.map(n=>Number(n.weightValue)));
Still inefficient as your looping throught the flatData twice instead of once:
```
max(flatData, n=>Number(n.weightValue));
```

2020-09-09 07:33 UTC, GordonSmith commented on packages/tree/src/DirectoryTree.ts
> +        }));
Also a double loop when one would suffice:
```
max(flatData, d=>this.textSize(d.weightValue, fontFamily, fontSize).width);
```

2020-09-09 14:45 UTC, GordonSmith approved these changes

2020-09-09 14:45 UTC, merged