feat: Add GMap option for error response callback
hpcc-systems/Visualization pull request #3716
Opened 2020-10-06 18:46 UTC by jbrundage

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2020-10-07 18:48 UTC, GordonSmith requested changes

2020-10-07 18:48 UTC, GordonSmith commented on packages/map/src/GMap.ts
> +GMap.prototype.publish("useStatusErrorCallback", false, "boolean", "If true, api responses without status 200 will be passed as arguments to 'statusErrorCallback'");
No need for "useStatusErrorCallback".

2020-10-07 18:48 UTC, GordonSmith commented on packages/map/src/GMap.ts
> +
By default this method should have the default code:  `console.error("Street View data not found for this location.");`

2020-10-07 18:48 UTC, GordonSmith commented on packages/map/src/GMap.ts
> +                if(context.useStatusErrorCallback()){
No need for `useStatusErrorCallback` just call the default implementation (and move the message in there).

2020-10-07 18:48 UTC, GordonSmith commented on packages/map/src/GMap.ts
> +    statusErrorCallback(response) {
Rename to "statusError" and it should follow the "click" pattern.

2020-10-07 18:48 UTC, GordonSmith commented on demos/gallery/samples/geospatial/Google Maps/StreetView3.js
> +};
Change to:
```
map.on("statusError", response=>{
  ...
});
```

2020-10-08 15:17 UTC, jbrundage commented
@GordonSmith this is ready

2020-10-08 15:27 UTC, GordonSmith approved these changes

2020-10-08 15:27 UTC, merged