feat(graph): Add params for d3 force
hpcc-systems/Visualization pull request #3768
Opened 2021-02-17 17:42 UTC by jbrundage

Fixes #3758

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2021-02-17 17:44 UTC, jbrundage commented
Before and After this change, but using the same publish properties:
![image](https://user-images.githubusercontent.com/1891935/108245107-e8e14600-711d-11eb-9da1-a16c9522742b.png)

2021-02-17 17:47 UTC, jbrundage commented
Before and after this change, but setting .forceDirectedMaxDistance(200)
![image](https://user-images.githubusercontent.com/1891935/108245416-41184800-711e-11eb-9044-5c7bcd884463.png)

2021-02-17 17:49 UTC, jbrundage commented
...and with .forceDirectedMinDistance(5) there's only a slight difference (it lessens the force severity when vertices are tightly packed):
![image](https://user-images.githubusercontent.com/1891935/108245669-8ccaf180-711e-11eb-8511-05d851a32f17.png)

2021-02-17 17:50 UTC, jbrundage commented
...and .forceDirectedForceStrength(0.1) pulls everything toward the middle:
![image](https://user-images.githubusercontent.com/1891935/108245793-b4ba5500-711e-11eb-82f5-73334f7b4a67.png)

2021-02-17 17:52 UTC, jbrundage commented
...and here's .forceDirectedForceStrength(0.05):
![image](https://user-images.githubusercontent.com/1891935/108246034-fba84a80-711e-11eb-9b32-74cd70ffce09.png)

2021-02-18 12:08 UTC, GordonSmith requested changes

2021-02-18 12:08 UTC, GordonSmith commented on packages/graph/package.json
> +        "d3-force": "2.1.1",
This change will not work in IE11 (do we care?) - I suspect your changes will work with 1.2.1 as well?

2021-02-18 12:08 UTC, GordonSmith commented on packages/graph/src/graph2/graph.ts
> +Graph2.prototype.publish("forceDirectedMinDistance", 1, "number", "Max distance between nodes", null, { disable: (w: Graph2) => w.layout().indexOf("ForceDirected") !== 0 });
Description is wrong

2021-02-19 09:13 UTC, GordonSmith approved these changes

2021-02-19 09:13 UTC, merged