feat: Add edgeColorColumn to DataGraph
hpcc-systems/Visualization pull request #3879
Opened 2021-11-16 15:14 UTC by jbrundage

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2021-11-16 15:15 UTC, jbrundage commented
@GordonSmith please review

2021-11-16 15:15 UTC, jbrundage commented
![image](https://user-images.githubusercontent.com/1891935/142012120-fb041e7c-b904-4281-90c6-d5bb566c854e.png)

2021-11-17 10:01 UTC, GordonSmith requested changes

2021-11-17 10:01 UTC, GordonSmith commented on packages/graph/src/graph2/graph.ts
> +                    })
This should be in the "update" section not the enter "section"

2021-11-17 10:01 UTC, GordonSmith commented on packages/graph/src/graph2/graph.ts
> +            })
This should be sufficent?

2021-11-17 10:03 UTC, GordonSmith requested changes
This is also failing to build.

2021-11-18 16:07 UTC, GordonSmith approved these changes

2021-11-18 16:12 UTC, merged