chore:  Refactor Graph2 to be more generic
hpcc-systems/Visualization pull request #4025
Opened 2022-09-26 11:41 UTC by GordonSmith

Not 100% complete, but GraphT has reduced dependency on IVertex/Vertex

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Checklist:
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2022-09-26 16:21 UTC, jeclrsg commented on packages/graph/src/graph2/graphT.ts
> +    resolveEventOrigin(): { origin: string, data } {
data is now any, is that right?

2022-09-26 18:41 UTC, GordonSmith commented on packages/graph/src/graph2/sankeyGraph.ts
> +        // const centroidIdx = this.indexOf(columns, this.vertexCentroidColumn(), "centroid");
I have reverted sankeyGraph.ts and fixed the errors with minimal change to the original...

2022-09-26 18:52 UTC, GordonSmith commented
@jeclrsg changes made

2022-09-26 20:26 UTC, jeclrsg requested changes
@GordonSmith There are some places where VSC is complaining about types. Some of them I didn't mention because I'm not sure if it's correct or not

2022-09-26 20:26 UTC, jeclrsg commented on packages/graph/src/graph2/graphT.ts
> +    resolveEventOrigin(): { origin: string, data } {
Looks like it could be undefined too, if dataStr was empty

2022-09-26 20:26 UTC, jeclrsg commented on packages/graph/src/graph2/graphT.ts
> +                this.highlightVerticies(null);
VSC is complaining about this null. I guess because of the explicit type on highlightVerticies, unlike highlightEdges?

2022-09-26 20:26 UTC, jeclrsg commented on packages/graph/src/graph2/graphT.ts
> +                this.highlightVerticies(null);
and here

2022-09-28 16:27 UTC, jeclrsg approved these changes

2022-09-28 18:21 UTC, merged