feat:  Parse the DefinitionList at source
hpcc-systems/Visualization pull request #4156
Opened 2024-01-19 16:50 UTC by GordonSmith

Ensure there are always "some" values for TimeLocalExecute

## Checklist:
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2024-01-19 19:33 UTC, jeclrsg requested changes
@GordonSmith maybe a small problem in that regex? Not sure, tbh. I think it works either way.

2024-01-19 19:33 UTC, jeclrsg commented on packages/comms/src/ecl/workunit.ts
> +const definitionRegex = /([a-zA-Z]:)?(.*[\\/])(.*)(\((\d+),(\d+)\))/;
I think forward slashes should also be escaped? `[\\\/]`

2024-01-22 15:58 UTC, GordonSmith commented
@jeclrsg converting to draft as there are some more changes that should go in here...

2024-01-23 14:40 UTC, jeclrsg approved these changes

2024-01-23 15:11 UTC, merged