feat:  Switch to esbuild and ESM first packaging
hpcc-systems/Visualization pull request #4238
Opened 2024-09-16 09:48 UTC by GordonSmith

BREAKING CHANGE: Changed type to "module" and dropped UMD support

## Checklist:
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:

2024-09-23 15:06 UTC, jeclrsg requested changes
@GordonSmith saw a couple of things in the observable-compiler area. I think all the other comments (the earlier ones) were just things I was wondering about.

2024-09-24 06:28 UTC, GordonSmith commented on packages/dataflow/package.json
> +        "clean": "rimraf --glob lib* types dist dist-test *.tsbuildinfo .turbo",
I think its related to nx + caching (which we are not using) - I had some stray folders from previous testing I suspect.

2024-09-24 06:30 UTC, GordonSmith commented on packages/dataflow/spec/index.browser.ts
> +jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000;
For the browser tests, Jasmine will download the Firefox runner and selenium web driver if needed, hence the longer timeout.

2024-09-24 07:59 UTC, GordonSmith commented on packages/dataflow/src/activities/concat.ts
> +import { Source, IterableActivity } from "./activity.ts";
Its part of the "esm standard".  TypeScript accepts either .js or .ts with a flag.

2024-09-24 09:26 UTC, GordonSmith commented on packages/observablehq-compiler/src/writer.ts
> +        const injections = imp.injections!.map(inj => {
Switched to double check for undefined and then use `[]`

2024-09-24 09:26 UTC, GordonSmith commented on packages/observablehq-compiler/src/util.ts
> +    const matches = url.match(/^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n?]+)/img) || [url];
Updated to throw on match error.

2024-09-24 13:12 UTC, jeclrsg approved these changes

2024-09-24 17:32 UTC, merged